-- les tables, version postgres.
-- execute tout seul par le conteneur au premier demarrage.
-- les differences avec sqlite sont marquees "sqlite :"

DROP TABLE IF EXISTS mouvements;
DROP TABLE IF EXISTS charges;
DROP TABLE IF EXISTS machines;
DROP TYPE  IF EXISTS etat_charge;
DROP TYPE  IF EXISTS type_mouvement;

-- un vrai type enumere, l'equivalent exact du type union TypeScript.
-- sqlite : ca n'existe pas, d'ou le CHECK (etat IN ...)
CREATE TYPE etat_charge    AS ENUM ('posee', 'en_transit', 'retiree');
CREATE TYPE type_mouvement AS ENUM ('depot', 'depart', 'arrivee', 'retrait');


CREATE TABLE machines (
    -- sqlite : INTEGER PRIMARY KEY se remplissait tout seul
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  TEXT NOT NULL UNIQUE,
    CONSTRAINT nom_non_vide CHECK (length(trim(nom)) > 0)
);


CREATE TABLE charges (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etat           etat_charge NOT NULL,
    machine_id     INTEGER REFERENCES machines(id) ON DELETE RESTRICT,
    destination_id INTEGER REFERENCES machines(id) ON DELETE RESTRICT,

    -- contraintes nommees. le nom ressort dans le message d'erreur,
    -- donc une api peut le traduire en message lisible
    CONSTRAINT etat_coherent CHECK (
        (etat = 'posee'      AND machine_id IS NOT NULL AND destination_id IS NULL)
     OR (etat = 'en_transit' AND machine_id IS NULL     AND destination_id IS NOT NULL)
     OR (etat = 'retiree'    AND machine_id IS NULL     AND destination_id IS NULL)
    ),
    CONSTRAINT pas_de_trajet_sur_place CHECK (
        machine_id IS NULL OR destination_id IS NULL OR machine_id <> destination_id
    )
);

-- une machine porte au plus une charge. le WHERE est obligatoire,
-- sinon deux palettes en transit se bloqueraient entre elles
CREATE UNIQUE INDEX idx_une_charge_par_machine
    ON charges (machine_id)
    WHERE machine_id IS NOT NULL;


CREATE TABLE mouvements (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    charge_id          INTEGER NOT NULL REFERENCES charges(id) ON DELETE CASCADE,
    type               type_mouvement NOT NULL,
    machine_depart_id  INTEGER REFERENCES machines(id) ON DELETE RESTRICT,
    machine_arrivee_id INTEGER REFERENCES machines(id) ON DELETE RESTRICT,

    -- un instant avec son fuseau. le seul type correct pour un evenement
    -- reel. sqlite : TIMESTAMP n'etait que du texte
    horodatage         TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT pas_dans_le_futur CHECK (horodatage <= now()),

    CONSTRAINT forme_du_mouvement CHECK (
        (type = 'depot'   AND machine_depart_id IS NULL     AND machine_arrivee_id IS NOT NULL)
     OR (type = 'depart'  AND machine_depart_id IS NOT NULL AND machine_arrivee_id IS NOT NULL)
     OR (type = 'arrivee' AND machine_depart_id IS NULL     AND machine_arrivee_id IS NOT NULL)
     OR (type = 'retrait' AND machine_depart_id IS NOT NULL AND machine_arrivee_id IS NULL)
    )
);

CREATE INDEX idx_mouvements_charge ON mouvements (charge_id, horodatage);
